# Generated by Django 3.2.5 on 2021-08-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vastu',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vedicastrology',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
