# Generated by Django 3.2.5 on 2021-08-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
